// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recados.API.Data;

#nullable disable

namespace Recados.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240317062755_Ini")]
    partial class Ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.Recado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mensagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Recados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mensagem = "Mensagem Recado 1",
                            Titulo = "Título Recado 1",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Mensagem = "Mensagem Recado 2",
                            Titulo = "Título Recado 2",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 3,
                            Mensagem = "Mensagem Recado 3",
                            Titulo = "Título Recado 3",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 4,
                            Mensagem = "Mensagem Recado 4",
                            Titulo = "Título Recado 4",
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("Shared.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Rafael@gmail.com",
                            Genero = 1,
                            Nome = "Rafael"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Fernando@gmail.com",
                            Genero = 1,
                            Nome = "Fernando"
                        });
                });

            modelBuilder.Entity("Shared.Models.Recado", b =>
                {
                    b.HasOne("Shared.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
